version: '3.7'
services:
  devcal-db-2018:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: devcal-db-2018
    env_file: db.2018.env
    volumes:
      - /mnt/data/devcal-db-2018:/var/opt/mssql
      - /mnt/backup/devcal-db-2018:/backup
    networks:
      - devcal-2018
    ports:
      - 127.0.0.1:1434:1433
    labels: 
      - "traefik.enable=false"
    restart: unless-stopped

  devcal-app-2018:
    image: devadventcalendar/devadventcalendar
    container_name: devcal-app-2018
    env_file: app.2018.env
    networks: 
      - devcal-2018
      - traefik
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.devcal-app-2018.entrypoints=https"
      - "traefik.http.routers.devcal-app-2018.rule=Host(`2018.devadventcalendar.pl`)"
      - "traefik.http.routers.devcal-app-2018.tls=true"
      - "traefik.http.routers.devcal-app-2018.tls.certresolver=le"
      - "traefik.http.routers.devcal-app-2018.service=devcal-app-2018"
      - "traefik.http.services.devcal-app-2018.loadbalancer.server.port=80"
    depends_on:
      - devcal-db-2018
    restart: unless-stopped

networks:
  traefik:
    external: true
  devcal-2018:
    external: true