version: '3.7'
services:
  db:
    image: microsoft/mssql-server-linux
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: "DevCal123!."
      ACCEPT_EULA: "Y"

  web:
    build:
      context: .
    ports:
      - 5000:80
      - 44394:443 
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    links:
      - db

  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - web