version: '3.7'
services:
  web:
    build:
      context: .
    ports:
      - 5000:80
      - 44394:443 
  proxy:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - web