version: '3.7'
services:
  db:
    image: microsoft/mssql-server-linux
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: "DevCal123!."
      ACCEPT_EULA: "Y"
    volumes:
      - dbdata:/var/lib/mysql

  web:
    build:
      context: .
    ports:
      - 5000:80
      - 44394:443 
    environment:
      ASPNETCORE_ENVIRONMENT: "Docker"
    depends_on:
      - db

  proxy:
    image: nginx:latest
    ports:
      - 8081:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      
  mailhog:
    image: mailhog/mailhog
    ports: 
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
    depends_on:
      - web
      
volumes:
  dbdata: