//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevLoggingMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoggingMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoggingMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevAdventCalendarCompetition.Resources.LoggingMessages", typeof(LoggingMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created an account using {Name} provider..
        /// </summary>
        public static string CreatedUserNameProvider {
            get {
                return ResourceManager.GetString("CreatedUserNameProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd podczas ładowania zewnętrznych danych logowania podczas potwierdzania..
        /// </summary>
        public static string LoadingDataError {
            get {
                return ResourceManager.GetString("LoadingDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created a new account with password..
        /// </summary>
        public static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User changed their password successfully..
        /// </summary>
        public static string PasswordIsChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordIsChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod musi być dostarczony do resetowania hasła..
        /// </summary>
        public static string ResetPasswordCodeError {
            get {
                return ResourceManager.GetString("ResetPasswordCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account locked out..
        /// </summary>
        public static string UserAccountIsLockedOut {
            get {
                return ResourceManager.GetString("UserAccountIsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged in..
        /// </summary>
        public static string UserIsLoggedIn {
            get {
                return ResourceManager.GetString("UserIsLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz najpierw potwierdzić swoje konto!.
        /// </summary>
        public static string UserIsNotConfirmed {
            get {
                return ResourceManager.GetString("UserIsNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged in with {Name} provider..
        /// </summary>
        public static string UserLoginProvider {
            get {
                return ResourceManager.GetString("UserLoginProvider", resourceCulture);
            }
        }
    }
}
