//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevAdventCalendarCompetition.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevAdventCalendarCompetition.Resources.ViewsMessages", typeof(ViewsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nas.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasjonat programowania, automatyzacji oraz linuxa. W wolnych chwilach uwielbia seriale, rower oraz podróże, zarówno bliższe jak i te dalsze..
        /// </summary>
        public static string AboutGrzegorzMutkowski {
            get {
                return ResourceManager.GetString("AboutGrzegorzMutkowski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konsultant Microsoft Power Platform. Do IT przeszedł w 2020 roku, po kilku latach pracy w branży marketingowej. W wolnych chwilach uczy się C# i JavaScript. Ceni zasady filozofii stoickiej i próbuję je stosować w praktyce, z różnym skutkiem..
        /// </summary>
        public static string AboutIgorBelczewski {
            get {
                return ResourceManager.GetString("AboutIgorBelczewski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student, który do projektu trafił szukając nowych wyzwań. Miłośnik kawy oraz filmów Marvela. W wolnym czasie lubi grać w planszowki ze znajomymi lub dokształcać się z zakresu ekonomii..
        /// </summary>
        public static string AboutKamilJarzebski {
            get {
                return ResourceManager.GetString("AboutKamilJarzebski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programista Java, który zmienił obóz z Oracle na Microsoft pod wpływem  .NET Core. Interesuje się tematyką sieci komputerowych, bezpieczeństwem aplikacji, a w wolnych chwilach lubi eksperymentować ze sztuką miksologii oraz eksplorować głębię mórz i polskich jezior..
        /// </summary>
        public static string AboutKamilSmieszek {
            get {
                return ResourceManager.GetString("AboutKamilSmieszek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trener z wieloletnią praktyką w zakresie nauczania technologii w obszarze IT, programista fullstack, ze szczególnym uwzględnieniem zakresu baz danych - głównie w obszarze technologii Microsoftu.  Specjalista, nauczyciel i partner biznesowy, który z wiedzą, umiejętnościami, pasją i zaangażowaniem wprowadza swoich słuchaczy w świat programowania..
        /// </summary>
        public static string AboutKrystianBrozek {
            get {
                return ResourceManager.GetString("AboutKrystianBrozek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student, a przede wszystkim pasjonat robotyki, gier komputerowych i GameJamów. Rozwijający wiedzę o C++, C# i Unity. Miłośnik historii oraz wszystkiego co wysoko - od górskich szczytów po odległe planety..
        /// </summary>
        public static string AboutKrzysztofSiera {
            get {
                return ResourceManager.GetString("AboutKrzysztofSiera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dotnetomaniak z niesłabnącym zapałem do rozwoju. Nie tylko twierdzący, że &quot;to zależy&quot; ale również starający się odpowiedzieć &quot;od czego&quot;. Pilny student - niedługo inżynier informatyki..
        /// </summary>
        public static string AboutMateuszGolombniak {
            get {
                return ResourceManager.GetString("AboutMateuszGolombniak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Współorganizator projektu od 2018 zajmujący się marketingiem, promocją i wszystkim, co nie jest kodem. Na co dzień wręcz odwrotnie - programista piszący w Javie, Kotlinie i właściwie w czym potrzeba. Do tego zdarza mu się poprowadzić szkolenie, wydać kurs, czy pomóc w organizacji jakiejś konferencji. Bloguje na &lt;a href=&quot;https://www.michalgellert.pl/&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot; class=&quot;link&quot;&gt;www.michalgellert.pl&lt;/a&gt;..
        /// </summary>
        public static string AboutMichalGellert {
            get {
                return ResourceManager.GetString("AboutMichalGellert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uczeń technikum lubiący w wolnym czasie jeździć na rowerze oraz motorze. Początkujący developer, piszący najwięcej kodu w Pythonie, próbujący różnych języków i technologii obecnie uczący się Darta, by móc przejść do Fluttera. Okazyjnie grzebiący w Linuxie oraz początkujący pasjonat open source. Osoba chcąca tworzyć społeczności szukająca swojej ścieżki oraz przyszłych projektów otwartych na rozwój..
        /// </summary>
        public static string AboutMichalPiechowiak {
            get {
                return ResourceManager.GetString("AboutMichalPiechowiak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programista .NET, fan(atyk) automatyzacji. Pasjonat programowania i czystego kodu. Aktywny uczestnik lokalnych konferencji i grup programistycznych. Po godzinach miłośnik książek, filmów, seriali i gier fantasy oraz sci-fi..
        /// </summary>
        public static string AboutPatrykLotzwi {
            get {
                return ResourceManager.GetString("AboutPatrykLotzwi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wesoły programista, który lubi poznawać nowych ludzi oraz brać udział w różnych interesujących przedsięwzięciach. W świecie IT rozwija się nieprzerwanie od 15 lat. Esteta, który docenia piękno sztuki, lubi grafikę komputerową oraz tworzyć filmy. Hobbystycznie fotografuje, pstrykając zdjęcia krajobrazu, ale również czerpie radość z realizacji reportaży. Zgłębia techniki karate, co daje mu siłę panować nad emocjami oraz przezwyciężać ból..
        /// </summary>
        public static string AboutPiotrKowalski {
            get {
                return ResourceManager.GetString("AboutPiotrKowalski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Manager w jednej z wrocławskich firm. W wolnym czasie pasjonat czytania kryminałów i thrillerów oraz aktywnego spędzania czasu na wycieczkach górskich..
        /// </summary>
        public static string AboutPiotrKrol {
            get {
                return ResourceManager.GetString("AboutPiotrKrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Główny organizator projektu od 2017 roku oraz programista. W projekcie  łączy w sobie wiele roli: lider, manager, developer, devops, analityk, tester oraz specjalista ds. marketingu. Po pracy prowadzi blog programistyczny &lt;a href=&quot;http://www.programmer-girl.com&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot; class=&quot;link&quot;&gt;www.programmer-girl.com&lt;/a&gt; Microsoft MVP i współorganizator Wrocławskiej grupy .NET &lt;a href=&quot;https://wrocnet.org/&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot; class=&quot;link&quot;&gt;https://wrocnet.org/&lt;/a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AboutWeronikaMularczyk {
            get {
                return ResourceManager.GetString("AboutWeronikaMularczyk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akceptuj.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostawiając tutaj swojego maila zgadzasz się na postanowienia regulaminu dostępnego tutaj.
        /// </summary>
        public static string AcceptTermsOfUse {
            get {
                return ResourceManager.GetString("AcceptTermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak dostępu.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To konto zostało zablokowane. Spróbuj ponownie później..
        /// </summary>
        public static string AccountBlockedDescription {
            get {
                return ResourceManager.GetString("AccountBlockedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzanie kontem.
        /// </summary>
        public static string AccountManagement {
            get {
                return ResourceManager.GetString("AccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie masz lokalnego loginu/hasła dla tej strony. Dodaj lokalne konto, żeby móc się logować..
        /// </summary>
        public static string AddLocalAccount {
            get {
                return ResourceManager.GetString("AddLocalAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowy test.
        /// </summary>
        public static string AddNewTest {
            get {
                return ResourceManager.GetString("AddNewTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj test.
        /// </summary>
        public static string AddTest {
            get {
                return ResourceManager.GetString("AddTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona Administratora.
        /// </summary>
        public static string AdminPage {
            get {
                return ResourceManager.GetString("AdminPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź to: &quot;barszcz&quot;.
        /// </summary>
        public static string AnswerIsBorsch {
            get {
                return ResourceManager.GetString("AnswerIsBorsch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiadasz na pytania &lt;br/&gt; i zbierasz punkty.
        /// </summary>
        public static string AnswerQuestions {
            get {
                return ResourceManager.GetString("AnswerQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple iPad 8-generacji 10,2&quot; 3GB/32GB.
        /// </summary>
        public static string AppleIPad {
            get {
                return ResourceManager.GetString("AppleIPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zestaw startowy Arduino od podstaw - z Arduino Uno.
        /// </summary>
        public static string Arduino {
            get {
                return ResourceManager.GetString("Arduino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arduino StarterKit K000007.
        /// </summary>
        public static string ArduinoStarterKit {
            get {
                return ResourceManager.GetString("ArduinoStarterKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagrody tygodni.
        /// </summary>
        public static string AwardsOfTheWeek {
            get {
                return ResourceManager.GetString("AwardsOfTheWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powrót.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wróć do zagadek.
        /// </summary>
        public static string BackToPuzzles {
            get {
                return ResourceManager.GetString("BackToPuzzles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilet na konferencję online BoilingFrogs 2021.
        /// </summary>
        public static string BoilingFrogs {
            get {
                return ResourceManager.GetString("BoilingFrogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblicz.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana hasła.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień hasło.
        /// </summary>
        public static string ChangeYourPassword {
            get {
                return ResourceManager.GetString("ChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Możesz również wesprzeć naszą zrzutkę, z której cały dochód przeznaczymy na Szlachetną Paczkę.
        /// </summary>
        public static string CharityAction {
            get {
                return ResourceManager.GetString("CharityAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz sposób uwierzytelniania dwuetapowego:.
        /// </summary>
        public static string Choose2Fa {
            get {
                return ResourceManager.GetString("Choose2Fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończ test wcześniej.
        /// </summary>
        public static string CompleteTestEalier {
            get {
                return ResourceManager.GetString("CompleteTestEalier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź hasło.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratulacje!.
        /// </summary>
        public static string Congrats {
            get {
                return ResourceManager.GetString("Congrats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Połącz swoje konto.
        /// </summary>
        public static string ConnectAccount {
            get {
                return ResourceManager.GetString("ConnectAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skontaktuj się z nami.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poprawna odpowiedź: {0}.
        /// </summary>
        public static string CorrectAnswer {
            get {
                return ResourceManager.GetString("CorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poprawne odpowiedzi.
        /// </summary>
        public static string CorrectAnswers {
            get {
                return ResourceManager.GetString("CorrectAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Załóż nowe konto.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DZIEŃ {0}.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Słuchawki Denon AH-GC25W.
        /// </summary>
        public static string DenonAHGC25W {
            get {
                return ResourceManager.GetString("DenonAHGC25W", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swapping to &lt;strong&gt;Development&lt;/strong&gt; environment will display more detailed information about the error that occurred..
        /// </summary>
        public static string DevelopmentErrorFullDescription1 {
            get {
                return ResourceManager.GetString("DevelopmentErrorFullDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Development environment should not be enabled in deployed applications&lt;/strong&gt;, as it can result in sensitive information from exceptions being displayed to end users. For local debugging, development environment can be enabled by setting the &lt;strong&gt;ASPNETCORE_ENVIRONMENT&lt;/strong&gt; environment variable to &lt;strong&gt;Development&lt;/strong&gt;, and restarting the application..
        /// </summary>
        public static string DevelopmentErrorFullDescription2 {
            get {
                return ResourceManager.GetString("DevelopmentErrorFullDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Mode.
        /// </summary>
        public static string DevelopmentMode {
            get {
                return ResourceManager.GetString("DevelopmentMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statystyki.
        /// </summary>
        public static string DisplayStatistics {
            get {
                return ResourceManager.GetString("DisplayStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I nie przegap najważniejszych wydarzeń!.
        /// </summary>
        public static string DontMissEvents {
            get {
                return ResourceManager.GetString("DontMissEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcesz zostać partnerem i wesprzeć dobrą inicjatywę w 2020 roku?.
        /// </summary>
        public static string DoYouWantToBePartner2020 {
            get {
                return ResourceManager.GetString("DoYouWantToBePartner2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chcesz zostać partnerem i wesprzeć dobrą inicjatywę w 2021 roku?.
        /// </summary>
        public static string DoYouWantToBePartner2021 {
            get {
                return ResourceManager.GetString("DoYouWantToBePartner2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten adres email już mamy w swojej bazie :).
        /// </summary>
        public static string EmailAlreadyInDatabase {
            get {
                return ResourceManager.GetString("EmailAlreadyInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzenie rejestracji.
        /// </summary>
        public static string EmailConfirmation {
            get {
                return ResourceManager.GetString("EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email potwierdzony..
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twój e-mail został potwierdzony. Naciśnij poniższy przycisk, aby się zalogować..
        /// </summary>
        public static string EmailConfirmedDescription {
            get {
                return ResourceManager.GetString("EmailConfirmedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email został już potwierdzony..
        /// </summary>
        public static string EmailForRegistrationConfirmed {
            get {
                return ResourceManager.GetString("EmailForRegistrationConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twój e-mail został już potwierdzony. Naciśnij poniższy przycisk, aby się zalogować..
        /// </summary>
        public static string EmailForRegistrationConfirmedDescription {
            get {
                return ResourceManager.GetString("EmailForRegistrationConfirmedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musisz najpierw potwierdzić swoje konto!.
        /// </summary>
        public static string EmailMustBeConfirmed {
            get {
                return ResourceManager.GetString("EmailMustBeConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono takiego konta..
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas zakończenia:.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz kod weryfikacyjny.
        /// </summary>
        public static string EnterVerifyCode {
            get {
                return ResourceManager.GetString("EnterVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj swój email.
        /// </summary>
        public static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Każdego dnia otwierasz &lt;br/&gt;okienko kalendarza.
        /// </summary>
        public static string EveryDayYouOpen {
            get {
                return ResourceManager.GetString("EveryDayYouOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd logowania.
        /// </summary>
        public static string ExternalLoginFailure {
            get {
                return ResourceManager.GetString("ExternalLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawne logowanie zewnętrznym serwisem.
        /// </summary>
        public static string ExternalLoginFailureDescription {
            get {
                return ResourceManager.GetString("ExternalLoginFailureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zostałeś pomyślnie uwierzytelniony za pomocą serwisu.
        /// </summary>
        public static string ExternalRegistrationDescriptionPart1 {
            get {
                return ResourceManager.GetString("ExternalRegistrationDescriptionPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz poniżej adres e-mail dla tej witryny i kliknij przycisk Zarejestruj, aby zakończyć rejestrację..
        /// </summary>
        public static string ExternalRegistrationDescriptionPart2 {
            get {
                return ResourceManager.GetString("ExternalRegistrationDescriptionPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niepoprawna próba logowania..
        /// </summary>
        public static string FailedLoginAttempt {
            get {
                return ResourceManager.GetString("FailedLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wydarzenie na FB.
        /// </summary>
        public static string FbEvent {
            get {
                return ResourceManager.GetString("FbEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostateczne wyniki poznasz w piątek, 25 grudnia.
        /// </summary>
        public static string FinalScoreDescription {
            get {
                return ResourceManager.GetString("FinalScoreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przypomnienie hasła.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeśli konto skojarzone z podanym mailem istnieje, na ten adres został wysłany link umożliwiający zmianę hasła..
        /// </summary>
        public static string ForgotPasswordConfirmationPart1 {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprawdź swoją skrzynkę :)..
        /// </summary>
        public static string ForgotPasswordConfirmationPart2 {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na podany adres email wyślemy Ci link do zmiany hasła.
        /// </summary>
        public static string ForgotPasswordDescription {
            get {
                return ResourceManager.GetString("ForgotPasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapomniałeś/aś hasła?.
        /// </summary>
        public static string ForgotPasswordQuestion {
            get {
                return ResourceManager.GetString("ForgotPasswordQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aby się zalogować..
        /// </summary>
        public static string ForLogging {
            get {
                return ResourceManager.GetString("ForLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pełny ranking.
        /// </summary>
        public static string FullList {
            get {
                return ResourceManager.GetString("FullList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdobywasz fajne &lt;br/&gt; nagrody.
        /// </summary>
        public static string GetCoolPrizes {
            get {
                return ResourceManager.GetString("GetCoolPrizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A oto prezent, jaki otrzymujesz od Elfów za otwarcie okienka.
        /// </summary>
        public static string GiftFromElfs {
            get {
                return ResourceManager.GetString("GiftFromElfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj odpowiedź!.
        /// </summary>
        public static string GiveUsYourAnswer {
            get {
                return ResourceManager.GetString("GiveUsYourAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedź poprawna!.
        /// </summary>
        public static string GoodAnswer {
            get {
                return ResourceManager.GetString("GoodAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystapił błąd podczas tworzenia nowego kalendarza..
        /// </summary>
        public static string GoogleCalendarError {
            get {
                return ResourceManager.GetString("GoogleCalendarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd z integracją, przepraszamy!.
        /// </summary>
        public static string GoogleCalendarFailureIntegrationInfo {
            get {
                return ResourceManager.GetString("GoogleCalendarFailureIntegrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integracja z kalendarzem Google.
        /// </summary>
        public static string GoogleCalendarIntegration {
            get {
                return ResourceManager.GetString("GoogleCalendarIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W tej sekcji możesz zintegrować DevAdventCalendar z Twoim kalendarzem Google..
        /// </summary>
        public static string GoogleCalendarIntegrationIntro {
            get {
                return ResourceManager.GetString("GoogleCalendarIntegrationIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeglądanie, edytowanie, udostępnianie i trwałe usuwanie wszystkich kalendarzy, do których masz dostęp w kalendarzu Google..
        /// </summary>
        public static string GoogleCalendarIntegrationPermission1 {
            get {
                return ResourceManager.GetString("GoogleCalendarIntegrationPermission1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetlanie i edytowanie wydarzeń we wszystkich kalendarzach..
        /// </summary>
        public static string GoogleCalendarIntegrationPermission2 {
            get {
                return ResourceManager.GetString("GoogleCalendarIntegrationPermission2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W celu utworzenia nowega kalendarza oraz dodania wydarzeń w trakcie trwania adwentu będziemy potrzebować następujących uprawnień:.
        /// </summary>
        public static string GoogleCalendarIntegrationPermissionInfo {
            get {
                return ResourceManager.GetString("GoogleCalendarIntegrationPermissionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomyślnie utworzono nowy kalendarz z wydarzeniami..
        /// </summary>
        public static string GoogleCalendarSuccess {
            get {
                return ResourceManager.GetString("GoogleCalendarSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomyślnie zintegrowałeś DevAdventCalendar ze swoim kalendarzem Google!.
        /// </summary>
        public static string GoogleCalendarSuccessfulIntegrationInfo {
            get {
                return ResourceManager.GetString("GoogleCalendarSuccessfulIntegrationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miłej zabawy 🎁.
        /// </summary>
        public static string GoogleCalendarSuccessfulIntegrationInfo2 {
            get {
                return ResourceManager.GetString("GoogleCalendarSuccessfulIntegrationInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwaga! Integracja działa, ale nasza aplikacja wciąż jeszcze czeka na zweryfikowanie przez Google..
        /// </summary>
        public static string GoogleCalendarVerificationInfo {
            get {
                return ResourceManager.GetString("GoogleCalendarVerificationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystapił błąd podczas tworzenia wydarzeń w nowym kalendarzu..
        /// </summary>
        public static string GoogleEventsError {
            get {
                return ResourceManager.GetString("GoogleEventsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Home Inteligentny Głośnik OEM.
        /// </summary>
        public static string GoogleHomeGlosnik {
            get {
                return ResourceManager.GetString("GoogleHomeGlosnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Home Hub.
        /// </summary>
        public static string GoogleHomeHub {
            get {
                return ResourceManager.GetString("GoogleHomeHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przejdź na.
        /// </summary>
        public static string GoTo {
            get {
                return ResourceManager.GetString("GoTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udanej &lt;br&gt; Zabawy.
        /// </summary>
        public static string HaveFun {
            get {
                return ResourceManager.GetString("HaveFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevAdventCalendar - inicjatywa łącząca tradycję kalendarza adwentowego z programowaniem. Celem jest stworzenie konkursu dla osób związanych ze światem IT..
        /// </summary>
        public static string HeadDescription {
            get {
                return ResourceManager.GetString("HeadDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DevAdventCalendar - programistyczny kalendarz adwentowy.
        /// </summary>
        public static string HeadTitle {
            get {
                return ResourceManager.GetString("HeadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5x bon 100 zł do Heliona.
        /// </summary>
        public static string Helion100 {
            get {
                return ResourceManager.GetString("Helion100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4x bon 150 zł do Heliona.
        /// </summary>
        public static string Helion150 {
            get {
                return ResourceManager.GetString("Helion150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak to działa?.
        /// </summary>
        public static string HowItWorks {
            get {
                return ResourceManager.GetString("HowItWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gdy na zegarze 20 wybije.
        /// </summary>
        public static string IntroParagraph1 {
            get {
                return ResourceManager.GetString("IntroParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to okienko swoją zagadkę odkryje....
        /// </summary>
        public static string IntroParagraph2 {
            get {
                return ResourceManager.GetString("IntroParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiec spiesz się i co dzień okienka otwieraj..
        /// </summary>
        public static string IntroParagraph3 {
            get {
                return ResourceManager.GetString("IntroParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdobywaj punkty i nagrody zbieraj!.
        /// </summary>
        public static string IntroParagraph4 {
            get {
                return ResourceManager.GetString("IntroParagraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT Startup &quot;Brudne Przetargi&quot;.
        /// </summary>
        public static string ItStartup {
            get {
                return ResourceManager.GetString("ItStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W tamtym roku wsparli nas.
        /// </summary>
        public static string LastYearPartners {
            get {
                return ResourceManager.GetString("LastYearPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dowiedz się więcej.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zablokowany.
        /// </summary>
        public static string LockOut {
            get {
                return ResourceManager.GetString("LockOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj się!.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj używając loginu i hasła.
        /// </summary>
        public static string LogInUsingPassword {
            get {
                return ResourceManager.GetString("LogInUsingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner główny.
        /// </summary>
        public static string MainPartner {
            get {
                return ResourceManager.GetString("MainPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagrody główne.
        /// </summary>
        public static string MainPrizes {
            get {
                return ResourceManager.GetString("MainPrizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje konto.
        /// </summary>
        public static string ManageYourAccount {
            get {
                return ResourceManager.GetString("ManageYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patroni medialni.
        /// </summary>
        public static string MediaPartners {
            get {
                return ResourceManager.GetString("MediaPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wesołych Świąt!.
        /// </summary>
        public static string MerryChristmas {
            get {
                return ResourceManager.GetString("MerryChristmas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestrować nowego użytkownika?.
        /// </summary>
        public static string NewRegistrationQuestion {
            get {
                return ResourceManager.GetString("NewRegistrationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dalej.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Głośnik Nillkin Traveler W2.
        /// </summary>
        public static string Nillkin {
            get {
                return ResourceManager.GetString("Nillkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie masz dostępu do tego zasobu..
        /// </summary>
        public static string NoAccessToResources {
            get {
                return ResourceManager.GetString("NoAccessToResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to otwartych okienek.
        /// </summary>
        public static string OpenPuzzles {
            get {
                return ResourceManager.GetString("OpenPuzzles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnerem dnia jest.
        /// </summary>
        public static string PartnerOfTheDay {
            get {
                return ResourceManager.GetString("PartnerOfTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnerzy.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset hasła.
        /// </summary>
        public static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje hasło zostało zresetowane!.
        /// </summary>
        public static string PasswordWasReset {
            get {
                return ResourceManager.GetString("PasswordWasReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planowany czas zakończenia:.
        /// </summary>
        public static string PlannedTestEnd {
            get {
                return ResourceManager.GetString("PlannedTestEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planowany czas rozpoczęcia:.
        /// </summary>
        public static string PlannedTestStart {
            get {
                return ResourceManager.GetString("PlannedTestStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziękujemy za zainteresowanie :) Na Twojej skrzynce powinna już czekać wiadomość, kliknij link w niej zawarty, aby potwierdzić swój email :).
        /// </summary>
        public static string PleaseConfirmEmail {
            get {
                return ResourceManager.GetString("PleaseConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapraszamy do kontaktu.
        /// </summary>
        public static string PleaseContactUs {
            get {
                return ResourceManager.GetString("PleaseContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikołaj ma dla Was wyjątkowe prezenty.
        /// </summary>
        public static string Presents {
            get {
                return ResourceManager.GetString("Presents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wypaśny tablet, słuchawki, głośniki, Raspberry Pi 4, bony i wiele innych. Sami sprawdźcie, dlaczego w tym roku warto być grzecznym..
        /// </summary>
        public static string PresentsDescription {
            get {
                return ResourceManager.GetString("PresentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiemy, wiemy, że się niecierpliwicie... Spokojnie ;) Odwiedzajcie naszą stronę, więcej informacji o nagrodach podamy już wkrótce!.
        /// </summary>
        public static string PresentsDescriptionNextEdition {
            get {
                return ResourceManager.GetString("PresentsDescriptionNextEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I w tym roku Mikołaj będzie miał dla Was wyjątkowe prezenty.
        /// </summary>
        public static string PresentsNextEdition {
            get {
                return ResourceManager.GetString("PresentsNextEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wstecz.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polityka prywatności.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagrody.
        /// </summary>
        public static string Prizes {
            get {
                return ResourceManager.GetString("Prizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnerzy nagród.
        /// </summary>
        public static string PrizesPartners {
            get {
                return ResourceManager.GetString("PrizesPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zagadka {0}.
        /// </summary>
        public static string Puzzle {
            get {
                return ResourceManager.GetString("Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zestaw Raspberry Pi 4B WiFi 8GB RAM.
        /// </summary>
        public static string RaspberryPi {
            get {
                return ResourceManager.GetString("RaspberryPi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zanim się zalogujesz, prosimy o potwierdzenie rejestracji..
        /// </summary>
        public static string RegisterConfirmationDescription {
            get {
                return ResourceManager.GetString("RegisterConfirmationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na Twój adres e-mail została wysłana wiadomość z linkiem potwierdzającym..
        /// </summary>
        public static string RegisterConfirmationDescriptionEmail {
            get {
                return ResourceManager.GetString("RegisterConfirmationDescriptionEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzenie rejestracji.
        /// </summary>
        public static string RegistrationConfirmation {
            get {
                return ResourceManager.GetString("RegistrationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zgoda na przetwarzanie danych.
        /// </summary>
        public static string RodoAgree {
            get {
                return ResourceManager.GetString("RodoAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brakuje zgody na przetwarzanie danych :(.
        /// </summary>
        public static string RodoAgreeMissing {
            get {
                return ResourceManager.GetString("RodoAgreeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoja pozycja będzie dostępna po zliczeniu wyników najbliższego rankingu (tygodnia nr 1/2/3 lub całego konkursu)..
        /// </summary>
        public static string ScoreDescription {
            get {
                return ResourceManager.GetString("ScoreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki już niedługo....
        /// </summary>
        public static string ScoresWillBeSoon {
            get {
                return ResourceManager.GetString("ScoresWillBeSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij kod weryfikacyjny.
        /// </summary>
        public static string SendCode {
            get {
                return ResourceManager.GetString("SendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij ponownie weryfikacyjny e-mail.
        /// </summary>
        public static string SendVerificationEmail {
            get {
                return ResourceManager.GetString("SendVerificationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw hasło.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stronę logowania.
        /// </summary>
        public static string SignInPage {
            get {
                return ResourceManager.GetString("SignInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pomyślnie się wylogowałeś..
        /// </summary>
        public static string SignOutSuccess {
            get {
                return ResourceManager.GetString("SignOutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wylogowany.
        /// </summary>
        public static string SingOutOther {
            get {
                return ResourceManager.GetString("SingOutOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to media społecznościowe:.
        /// </summary>
        public static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Głośnik Sony SRS-XB23.
        /// </summary>
        public static string SonySRSXB23 {
            get {
                return ResourceManager.GetString("SonySRSXB23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpocznij.
        /// </summary>
        public static string StartTest {
            get {
                return ResourceManager.GetString("StartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czas rozpoczęcia:.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysłana poprawna odpowiedź.
        /// </summary>
        public static string StatsCorrect {
            get {
                return ResourceManager.GetString("StatsCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pytanie.
        /// </summary>
        public static string StatsTestNumber {
            get {
                return ResourceManager.GetString("StatsTestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne odpowiedzi.
        /// </summary>
        public static string StatsWrong {
            get {
                return ResourceManager.GetString("StatsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Test zakończony.
        /// </summary>
        public static string StatusTestIsOver {
            get {
                return ResourceManager.GetString("StatusTestIsOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz się na newsletter.
        /// </summary>
        public static string SubscribeToNewsletter {
            get {
                return ResourceManager.GetString("SubscribeToNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niespodzianka.
        /// </summary>
        public static string Surprise {
            get {
                return ResourceManager.GetString("Surprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulamin.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw, ile ma trwać test (w minutach).
        /// </summary>
        public static string TestDuration {
            get {
                return ResourceManager.GetString("TestDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to domyślnie  20 minut.
        /// </summary>
        public static string TestDurationDefaults {
            get {
                return ResourceManager.GetString("TestDurationDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test się zakończył.
        /// </summary>
        public static string TestHasEnded {
            get {
                return ResourceManager.GetString("TestHasEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test {0} się jeszcze nie rozpoczął. Proszę poczekaj na otwarcie testu..
        /// </summary>
        public static string TestIsNotYetStarted {
            get {
                return ResourceManager.GetString("TestIsNotYetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test {0} sie zakończył. Sprawdź.
        /// </summary>
        public static string TestIsOver {
            get {
                return ResourceManager.GetString("TestIsOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test się nie rozpoczął.
        /// </summary>
        public static string TestNotStarted {
            get {
                return ResourceManager.GetString("TestNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poprzedni test nie zakończył się.
        /// </summary>
        public static string TestPreviousNotEnded {
            get {
                return ResourceManager.GetString("TestPreviousNotEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wyniku testu..
        /// </summary>
        public static string TestResults {
            get {
                return ResourceManager.GetString("TestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testy jeszcze się nie zakończyły.
        /// </summary>
        public static string TestsAreActive {
            get {
                return ResourceManager.GetString("TestsAreActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test rozpoczął się.
        /// </summary>
        public static string TestStarted {
            get {
                return ResourceManager.GetString("TestStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziękujemy! Bez Was nie było by to możliwe!.
        /// </summary>
        public static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziękujemy za potwierdzenie subskrypcji! Teraz wiemy, że Ty to Ty :).
        /// </summary>
        public static string ThankYouForSubscription {
            get {
                return ResourceManager.GetString("ThankYouForSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd!.
        /// </summary>
        public static string ThereIsError {
            get {
                return ResourceManager.GetString("ThereIsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika będzie wyświetlana tylko na liście wyników.
        /// </summary>
        public static string ToolTipUserName {
            get {
                return ResourceManager.GetString("ToolTipUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma punktów.
        /// </summary>
        public static string TotalScore {
            get {
                return ResourceManager.GetString("TotalScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Całkowity czas odpowiedzi (s).
        /// </summary>
        public static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lub zaloguj przez.
        /// </summary>
        public static string UseOtherLogin {
            get {
                return ResourceManager.GetString("UseOtherLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho ho! Już odpowiedziałeś na to pytanie, brawo :).
        /// </summary>
        public static string UserAlreadyAnswered {
            get {
                return ResourceManager.GetString("UserAlreadyAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa użytkownika.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Możesz teraz ustawić sobie nazwę użytkownika! Nazwa ta będzie widoczna publicznie w tabeli wyników..
        /// </summary>
        public static string UserNameChangeNotification {
            get {
                return ResourceManager.GetString("UserNameChangeNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weryfikacja.
        /// </summary>
        public static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunęliśmy Twój adres email z bazy.
        /// </summary>
        public static string WeDeletedYourEmail {
            get {
                return ResourceManager.GetString("WeDeletedYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tydzień {0}.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki dla pierwszego tygodnia poznasz we wtorek, 8 grudnia po godzinie 13:00..
        /// </summary>
        public static string Week1ScoreDescription {
            get {
                return ResourceManager.GetString("Week1ScoreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki dla drugiego tygodnia poznasz we wtorek, 15 grudnia po godzinie 13:00..
        /// </summary>
        public static string Week2ScoreDescription {
            get {
                return ResourceManager.GetString("Week2ScoreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyniki dla trzeciego tygodnia poznasz we wtorek, 22 grudnia po godzinie 13:00..
        /// </summary>
        public static string Week3ScoreDescription {
            get {
                return ResourceManager.GetString("Week3ScoreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnerzy tygodni.
        /// </summary>
        public static string WeeklyPartners {
            get {
                return ResourceManager.GetString("WeeklyPartners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numer tygodnia (1, 2, 3 lub 4 - dla wszystkich wyników).
        /// </summary>
        public static string WeekNumber {
            get {
                return ResourceManager.GetString("WeekNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapraszamy do tegorocznej edycji ;).
        /// </summary>
        public static string WelcomeToTheGame {
            get {
                return ResourceManager.GetString("WelcomeToTheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gramy do&lt;br&gt;24 grudnia.
        /// </summary>
        public static string WePlayUntilDecember {
            get {
                return ResourceManager.GetString("WePlayUntilDecember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie martw się, dla uproszczenia usuniemy nadmiarowe spacje z odpowiedzi.
        /// </summary>
        public static string WeRemovedWhiteSpaces {
            get {
                return ResourceManager.GetString("WeRemovedWhiteSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapnij pasy! Startujemy już za.
        /// </summary>
        public static string WeStartIn {
            get {
                return ResourceManager.GetString("WeStartIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serwis wykorzystuje pliki cookies. Korzystając ze strony wyrażasz zgodę na wykorzystywanie plików cookies..
        /// </summary>
        public static string WeUseCookies {
            get {
                return ResourceManager.GetString("WeUseCookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błędne odpowiedzi.
        /// </summary>
        public static string WrongAnswers {
            get {
                return ResourceManager.GetString("WrongAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Źle! Spróbuj ponownie :).
        /// </summary>
        public static string WrongTryAgain {
            get {
                return ResourceManager.GetString("WrongTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xiaomi Mi Band 5.
        /// </summary>
        public static string XiaomiBand5 {
            get {
                return ResourceManager.GetString("XiaomiBand5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedziałeś poprawnie we wszystkich otwartych do tej pory okienkach..
        /// </summary>
        public static string YouAnsweredCorrectly {
            get {
                return ResourceManager.GetString("YouAnsweredCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niestety, spóźniłeś się z odpowiedzią na to pytanie :(.
        /// </summary>
        public static string YouAreLateWithAnswer {
            get {
                return ResourceManager.GetString("YouAreLateWithAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedziano:.
        /// </summary>
        public static string YouHaveAnswered {
            get {
                return ResourceManager.GetString("YouHaveAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie odpowiedziałeś jeszcze na żadną zagadkę....
        /// </summary>
        public static string YouHaventAnswered {
            get {
                return ResourceManager.GetString("YouHaventAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoja odpowiedź.
        /// </summary>
        public static string YourAnswer {
            get {
                return ResourceManager.GetString("YourAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje statystyki wyglądają następująco:.
        /// </summary>
        public static string YourStats {
            get {
                return ResourceManager.GetString("YourStats", resourceCulture);
            }
        }
    }
}
