//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevAdventCalendarCompetition.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevAdventCalendarCompetition.Resources.ViewsMessages", typeof(ViewsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poprawna odpowiedź: {0}.
        /// </summary>
        public static string CorrectAnswer {
            get {
                return ResourceManager.GetString("CorrectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten adres email już mamy w swojej bazie :).
        /// </summary>
        public static string EmailAlreadyInDatabase {
            get {
                return ResourceManager.GetString("EmailAlreadyInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A oto prezent, jaki otrzymujesz od Elfów za otwarcie okienka.
        /// </summary>
        public static string GiftFromElfs {
            get {
                return ResourceManager.GetString("GiftFromElfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gdy na zegarze 20 wybije.
        /// </summary>
        public static string IntroParagraph1 {
            get {
                return ResourceManager.GetString("IntroParagraph1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to okienko swoją zagadkę odkryje....
        /// </summary>
        public static string IntroParagraph2 {
            get {
                return ResourceManager.GetString("IntroParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiec spiesz się i co dzień okienka otwieraj..
        /// </summary>
        public static string IntroParagraph3 {
            get {
                return ResourceManager.GetString("IntroParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdobywaj punkty i nagrody zbieraj!.
        /// </summary>
        public static string IntroParagraph4 {
            get {
                return ResourceManager.GetString("IntroParagraph4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zagadka {0}.
        /// </summary>
        public static string Puzzle {
            get {
                return ResourceManager.GetString("Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brakuje zgody na przetwarzanie danych :(.
        /// </summary>
        public static string RodoAgreeMissing {
            get {
                return ResourceManager.GetString("RodoAgreeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyślij.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsorem dnia jest.
        /// </summary>
        public static string SponsorOfTheDay {
            get {
                return ResourceManager.GetString("SponsorOfTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziękujemy za potwierdzenie subskrypcji! Teraz wiemy, że Ty to Ty :).
        /// </summary>
        public static string ThankYouForSubscription {
            get {
                return ResourceManager.GetString("ThankYouForSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ho ho! Już odpowiedziałeś na to pytanie, brawo :).
        /// </summary>
        public static string UserAlreadyAnswered {
            get {
                return ResourceManager.GetString("UserAlreadyAnswered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usunęliśmy Twój adres email z bazy.
        /// </summary>
        public static string WeDeletedYourEmail {
            get {
                return ResourceManager.GetString("WeDeletedYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie martw się, dla uproszczenia usuniemy spacje z odpowiedzi.
        /// </summary>
        public static string WeRemovedWhiteSpaces {
            get {
                return ResourceManager.GetString("WeRemovedWhiteSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niestety, spóźniłeś się z odpowiedzią na to pytanie :(.
        /// </summary>
        public static string YouAreLateWithAnswer {
            get {
                return ResourceManager.GetString("YouAreLateWithAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dziękujemy za zainteresowanie :) Na Twojej skrzynce powinna już czekać wiadomość, kliknij link w niej zawarty, aby potwierdzić swój email :).
        /// </summary>
        public static string YouHaveEmailPleaseConfirm {
            get {
                return ResourceManager.GetString("YouHaveEmailPleaseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoja odpowiedź.
        /// </summary>
        public static string YourAnswer {
            get {
                return ResourceManager.GetString("YourAnswer", resourceCulture);
            }
        }
    }
}
