# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- deployment: target_test
  displayName: 'Deployment target test'
  environment:
    name:  Server
    resourceType: VirtualMachine
    tags: dev
  strategy:
    runOnce:
      deploy:
        steps:
        - script: docker ps --filter name=devcal*

