parameters:
  environment: ''

jobs:
- deployment: Deploy_${{ parameters.environment }}
  displayName: Deploy DevAdventCalendar ${{ parameters.environment }}
  environment:
    name: ${{ parameters.environment }}
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - task: DownloadSecureFile@1
          displayName: 'Download app secrets'
          inputs:
            secureFile: app.${{ parameters.environment }}.env
            retryCount: 5
            
        - task: DownloadSecureFile@1
          displayName: 'Download database secrets'
          inputs:
            secureFile: db.${{ parameters.environment }}.env
            retryCount: 5
            
        - task: CopyFiles@2
          displayName: 'Copy env files to target folder'
          inputs:
            SourceFolder: '$(Agent.TempDirectory)'
            Contents: '**/*.env'
            TargetFolder: '$(System.DefaultWorkingDirectory)/src/DevAdventCalendarCompetition'
            
        - task: DockerCompose@0
          displayName: 'Pull images'
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'GitHub Package Registry'
            dockerComposeFile: '$(System.DefaultWorkingDirectory)/src/DevAdventCalendarCompetition/docker-compose.uat.yml'
            projectName: 'devcal-${{ parameters.environment }}'
            dockerComposeCommand: pull

        - task: DockerCompose@0
          displayName: 'Deploy images'
          inputs:
            containerregistrytype: 'Container Registry'
            dockerRegistryEndpoint: 'GitHub Package Registry'
            dockerComposeFile: '$(System.DefaultWorkingDirectory)/src/DevAdventCalendarCompetition/docker-compose.uat.yml'
            projectName: 'devcal-${{ parameters.environment }}'
            dockerComposeCommand: 'up -d'