// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis. // <auto-generated/>
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using DevAdventCalendarCompetition.Repository;
using DevAdventCalendarCompetition.Repository.Context;
using DevAdventCalendarCompetition.Repository.Models;
using DevAdventCalendarCompetition.Services;
using DevAdventCalendarCompetition.Services.Models;
using DevAdventCalendarCompetition.Services.Profiles;
using DevAdventCalendarCompetition.Tests.AutoFixture;
using FluentAssertions;
using Xunit;

namespace DevAdventCalendarCompetition.Tests.IntegrationTests
{
    public class AdminServiceTests : IntegrationTestBase
    {
        public AdminServiceTests()
            : base()
        {
        }

        [Theory]
        [TestWithNumberWithoutAnswersData]
        public void GetAllTests_ReturnsAllTests(List<Test> testList)
        {
            using (var context = new ApplicationDbContext(this.ContextOptions))
            {
                context.AddRange(testList);
                context.SaveChanges();
            }

            using (var context = new ApplicationDbContext(this.ContextOptions))
            {
                var adminService = PrepareSUT(context);

                var result = adminService.GetAllTests();

                result.Should().BeOfType<List<TestDto>>();
                result.Count.Should().Be(testList.Count);
            }
        }

        [Theory]
        [TestWithNumberWithoutAnswersData]
        public void GetPreviousTest_ReturnsPreviousTest(Test currentTest, Test previousTest)
        {
            using (var context = new ApplicationDbContext(this.ContextOptions))
            {
                context.AddRange(currentTest, previousTest);
                context.SaveChanges();
            }

            using (var context = new ApplicationDbContext(this.ContextOptions))
            {
                var adminService = PrepareSUT(context);

                var result = adminService.GetPreviousTest(currentTest.Number);

                result.Should().BeOfType<TestDto>();
                result.Number.Should().Be(previousTest.Number);
                result.StartDate.Should().Be(previousTest.StartDate);
                result.EndDate.Should().Be(previousTest.EndDate);
            }
        }

        [Theory]
        [TestWithNumberWithoutAnswersData]
        public void AddTest_ValidTest_AddsCorrectAmountOfAnswers(TestDto testDto)
        {
            using (var context = new ApplicationDbContext(this.ContextOptions))
            {
                var adminService = PrepareSUT(context);

                adminService.AddTest(testDto);
            }

            using (var context = new ApplicationDbContext(this.ContextOptions))
            {
                var result = context.Tests.SingleOrDefault(t => t.Id == testDto.Id);
                result.HashedAnswers.Count.Should().Be(3);
            }
        }

        [Fact]
        public void AddTest_NullTest_ThrowsException()
        {
            using (var context = new ApplicationDbContext(this.ContextOptions))
            {
                var adminService = PrepareSUT(context);

                Action act = () => adminService.AddTest(null);

                act.Should().Throw<ArgumentNullException>();
            }
        }

        [Theory]
        [TestWithNumberWithoutAnswersData]
        public void UpdateTestDates_ParsableMinutes_UpdatesTestDates(Test test)
        {
            var minutes = 30;
            var minutesString = "30";
            using (var context = new ApplicationDbContext(this.ContextOptions))
            {
                context.Tests.Add(test);
                context.SaveChanges();
            }

            using (var context = new ApplicationDbContext(this.ContextOptions))
            {
                var adminService = PrepareSUT(context);
                adminService.UpdateTestDates(test.Id, minutesString);
            }

            using (var context = new ApplicationDbContext(this.ContextOptions))
            {
                var result = context.Tests.SingleOrDefault(t => t.Id == test.Id);
                result.StartDate.Should().BeCloseTo(DateTime.Now, 1000);
                result.EndDate.Should().BeCloseTo(DateTime.Now.AddMinutes(minutes), 1000);
            }
        }

        [Theory]
        [TestWithNumberWithoutAnswersData]
        public void UpdateTestDates_NotParsableMinutes_UpdatesTestDatesWithDefaultMinutesValue(Test test)
        {
            var defaultMinutes = 20;
            var notParsableMinutesString = "minuta";
            using (var context = new ApplicationDbContext(this.ContextOptions))
            {
                context.Tests.Add(test);
                context.SaveChanges();
            }

            using (var context = new ApplicationDbContext(this.ContextOptions))
            {
                var adminService = PrepareSUT(context);
                adminService.UpdateTestDates(test.Id, notParsableMinutesString);
            }

            using (var context = new ApplicationDbContext(this.ContextOptions))
            {
                var result = context.Tests.SingleOrDefault(t => t.Id == test.Id);
                result.StartDate.Should().BeCloseTo(DateTime.Now, 1000);
                result.EndDate.Should().BeCloseTo(DateTime.Now.AddMinutes(defaultMinutes), 1000);
            }
        }

        [Theory]
        [TestWithNumberWithoutAnswersData]
        public void UpdateTestEndDate_ValidDate_UpdatesTestEndDate(Test test, DateTime newDate)
        {
            using (var context = new ApplicationDbContext(this.ContextOptions))
            {
                context.Tests.Add(test);
                context.SaveChanges();
            }

            using (var context = new ApplicationDbContext(this.ContextOptions))
            {
                var adminService = PrepareSUT(context);
                adminService.UpdateTestEndDate(test.Id, newDate);
            }

            using (var context = new ApplicationDbContext(this.ContextOptions))
            {
                var result = context.Tests.SingleOrDefault(t => t.Id == test.Id);
                result.EndDate.Should().Be(newDate);
            }
        }

        private static AdminService PrepareSUT(ApplicationDbContext context)
        {
            var mapper = new MapperConfiguration(cfg => cfg.AddMaps(typeof(TestProfile))).CreateMapper();
            var testRepository = new TestRepository(context);
            var testAnswerRepository = new UserTestAnswersRepository(context);
            var stringHasher = new StringHasher(new HashParameters(100, new byte[] { 1, 2 }));
            return new AdminService(testRepository, testAnswerRepository, mapper, stringHasher);
        }
    }
}
