// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis. // <auto-generated/>

using System;
using System.Collections.Generic;

namespace DevAdventCalendarCompetition.Services.Models
{
    public class NewCalendarDto
    {
        public string Summary { get; set; }
    }

    public class CalendarDto
    {
        public string Id { get; set; }
    }

    public class EventsDto
    {
        public string Summary { get; set; }

        public string Location { get; set; }

        public StartDate Start { get; set; }

        public EndDate End { get; set; } = new EndDate();

        // https://tools.ietf.org/html/rfc5545#section-3.8.5
        public List<string> Recurrence { get; set; } 
    }

    public class StartDate
    {
        public DateTime DateTime { get; set; } = DateTime.Now.AddHours(2);
        public string TimeZone { get; set; } = @"Europe/Warsaw";
    }

    public class EndDate
    {
        public DateTime DateTime { get; set; } = DateTime.Now.AddHours(3);
        public string TimeZone { get; set; } = @"Europe/Warsaw";
    }

    public class CalendarList
    {
        public string Kind { get; set; }

        public string Etag { get; set; }

        public string NextSyncToken { get; set; }

#pragma warning disable CA2227 // Collection properties should be read only
        public List<Item> Items { get; set; }
#pragma warning restore CA2227 // Collection properties should be read only
    }

    public class Item
    {
        public string Kind { get; set; }

        public string Etag { get; set; }

        public string Id { get; set; }

        public string Summary { get; set; }

        public string TimeZone { get; set; }

        public string ColorId { get; set; }

        public string BackgroundColor { get; set; }

        public string ForegroundColor { get; set; }

        public bool Selected { get; set; }

        public string AccessRole { get; set; }

#pragma warning disable CA2227 // Collection properties should be read only
        public List<DefaultReminder> DefaultReminders { get; set; }
#pragma warning restore CA2227 // Collection properties should be read only

        public NotificationSettings NotificationSettings { get; set; }

        public bool Primary { get; set; }

        public ConferenceProperties ConferenceProperties { get; set; }

        public string Description { get; set; }

        public string Location { get; set; }

        public string SummaryOverride { get; set; }
    }

    public class NotificationSettings
    {
#pragma warning disable CA2227 // Collection properties should be read only
        public List<Notification> Notifications { get; set; }
#pragma warning restore CA2227 // Collection properties should be read only
    }

    public class Notification
    {
        public string Type { get; set; }

        public string Method { get; set; }
    }

    public class ConferenceProperties
    {
#pragma warning disable CA2227 // Collection properties should be read only
        public List<string> AllowedConferenceSolutionTypes { get; set; }
#pragma warning restore CA2227 // Collection properties should be read only
    }

    public class DefaultReminder
    {
        public string Method { get; set; }

        public int Minutes { get; set; }
    }

}
