// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis. // <auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace DevAdventCalendarCompetition.Repository.Migrations
{
    public partial class TimespanConversion : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AnsweringTimeOffset",
                table: "UserTestCorrectAnswers"
                );
            migrationBuilder.AddColumn<long>(
                name: "AnsweringTimeOffset",
                table: "UserTestCorrectAnswers",
                nullable: false
            );
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AnsweringTimeOffset",
                table: "UserTestCorrectAnswers"
            );
            migrationBuilder.AddColumn<TimeSpan>(
                name: "AnsweringTimeOffset",
                table: "UserTestCorrectAnswers",
                nullable: false,
                type: "time"
            );
        }
    }
}
