// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis. // <auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

namespace DevAdventCalendarCompetition.Repository.Migrations
{
    public partial class DropCompositeKey : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_TestAnswers",
                table: "TestAnswers");

            migrationBuilder.AddPrimaryKey(
                name: "PK_TestAnswers",
                table: "TestAnswers",
                column: "Id");

            migrationBuilder.CreateIndex(
                name: "IX_TestAnswers_TestId",
                table: "TestAnswers",
                column: "TestId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropPrimaryKey(
                name: "PK_TestAnswers",
                table: "TestAnswers");

            migrationBuilder.DropIndex(
                name: "IX_TestAnswers_TestId",
                table: "TestAnswers");

            migrationBuilder.AddPrimaryKey(
                name: "PK_TestAnswers",
                table: "TestAnswers",
                columns: new[] { "TestId", "Id" });
        }
    }
}
