// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis. // <auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

namespace DevAdventCalendarCompetition.Repository.Migrations
{
    public partial class AddTestUser : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "AspNetUsers",
                columns: new[] { "Id", "AccessFailedCount", "ConcurrencyStamp", "Email", "EmailConfirmed", "LockoutEnabled", "LockoutEnd", "NormalizedEmail", "NormalizedUserName", "PasswordHash", "PhoneNumber", "PhoneNumberConfirmed", "SecurityStamp", "TwoFactorEnabled", "UserName" },
                values: new object[] { "c611530e-bebd-41a9-ace2-951550edbfa0", 0, "e4de8553-5c8e-46b1-ab5a-19052617edd2", "devadventcalendar@gmail.com", true, false, null, "DEVADVENTCALENDAR@GMAIL.COM", "DEVADVENTCALENDAR@GMAIL.COM", "AQAAAAEAACcQAAAAEEP5eQn4QlBy8BIluF8TjgbbgFJNJsG6RiPFRDqUXjfNlza1St6dhORcOj3vF1w7jA==", null, false,"DWAXVN2W4U5J3KSGI7V7KPLU3GBWFVJL", false, "devadventcalendar@gmail.com" });

            migrationBuilder.InsertData(
                table: "AspNetUserRoles",
                columns: new[] { "UserId", "RoleId" },
                values: new object[] { "c611530e-bebd-41a9-ace2-951550edbfa0", "1" });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                table: "AspNetUserRoles",
                keyColumn: "UserId",
                keyValue: "c611530e-bebd-41a9-ace2-951550edbfa0"
            );

            migrationBuilder.DeleteData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "c611530e-bebd-41a9-ace2-951550edbfa0"
            );
        }
    }
}
