jobs:
- deployment: Deploy
  displayName: Deploy
  environment:
    name: server
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - script: hostname