trigger:
- master

jobs:
- deployment: Deploy
  displayName: Deploy
  environment:
    name: server
    resourceType: VirtualMachine
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self

        - template: steps/docker-compose.yaml
          parameterts:
            stage: $(Stage)