name: Pull Request verification

on: [pull_request]

jobs:

  build:
 
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.200
        
    - name: Build
      run: dotnet build -c Release --no-cache ./src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.sln
        
    - name: Run the Unit and Integration Tests
      run: dotnet test -c Release --no-build ./src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.sln
      
    - name: Run Code Coverage
      run: dotnet test -c Release --no-build /p:CollectCoverage=true /p:CoverletOutput="../" /p:ExcludeByFile=\"**/Migrations/**/*%2c**/Models/**/*%2c**/Views/**/*\" /p:MergeWith="../coverage.json" /maxcpucount:1 /p:CoverletOutputFormat=\"json,opencover\" ./src/DevAdventCalendarCompetition/DevAdventCalendarCompetition.sln
    
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./src/DevAdventCalendarCompetition/coverage.opencover.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Build the Docker image
      if: success()
      run: |
        cd src/DevAdventCalendarCompetition
        docker build . --file Dockerfile --tag devadventcalendar/devadventcalendar:2019
