name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        cd src/DevAdventCalendarCompetition 
        docker build . --file Dockerfile --tag devadventcalendar/devadventcalendar:2019
    - name: Push the Docker image
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: |
        docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
        docker push devadventcalendar/devadventcalendar:2019