name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image
      run: |
        cd src/DevAdventCalendarCompetition 
        docker build . --file Dockerfile --tag devadventcalendar/devadventcalendar:2019
    - name: Push the Docker image
      run: docker push devadventcalendar/devadventcalendar:2019