name: Pull Request verification

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v1
    - name: Build and test src code
      run: |
        cd src/DevAdventCalendarCompetition
        dotnet restore
        dotnet build
        dotnet test
        docker build . --file Dockerfile --tag devadventcalendar/devadventcalendar:2019
